version: '3.2'

networks:
  go-bookstore-network:

services:
  dblocal:
    image: postgres:12.12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: go-bookstore-db
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - go-bookstore-network